# Generated by Django 6.0.5 on 2026-05-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop', 'Pop'), ('Jazz', 'Jazz'), ('R&B', 'Rnb'), ('Metal', 'Metal'), ('Country', 'Country'), ('Dance', 'Dance'), ('Hip Hop', 'Hip Hop'), ('Other', 'Other')], max_length=30),
        ),
    ]
